[package]
name = "markdown_img_url_editor_rust"
version = "1.0.1"
authors = ["yumetodo <yume-wikijp@live.jp>"]
edition = "2018"
description = "![alt](I want to edit here)"
repository = "https://github.com/yumetodo/markdown_img_url_editor_rust.git"
license = "MIT"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
pulldown-cmark = "0.6.1"
pulldown-cmark-to-cmark = "2.0.1"
wasm-bindgen = "0.2.58"
js-sys = "0.3.35"

[lib]
crate-type = ["cdylib"]
